# Generated by Django 3.1.4 on 2021-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201231_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoposts',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
