# Generated by Django 3.1.4 on 2021-01-02 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210101_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
